Inertia\WinspireBundle\Entity\Category:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 128
        slug:
            type: string
            length: 128
        sf_id:
            type: string
            length: 256
        is_dirty:
            type: boolean
        is_active:
            type: boolean
    oneToMany:
        experience:
            targetEntity: Experience
            mappedBy: category