Inertia\WinspireBundle\Entity\Page:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        section:
            type: string
            length: 128
        title:
            type: text
        description:
            type: text
        slug:
            type: string
            length: 128
        content:
            type: text
        image:
            type: string
            length: 128
        sort:
            type: integer
        sf_id:
            type: string
            length: 256
        is_dirty:
            type: boolean
        is_active:
            type: boolean