Inertia\WinspireBundle\Entity\Testimonial:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 128
        title:
            type: string
            length: 128
        company:
            type: string
            length: 128
        quote:
            type: text
        sf_id:
            type: string
            length: 256
        is_dirty:
            type: boolean
        is_active:
            type: boolean